# Generated by Django 3.1.5 on 2021-01-08 10:35

from django.db import migrations
from users.models import User


def initial_admins_add(apps, schema_editor):

    regular_user = User.objects.create_user(
        'user1',
        password='user1',
        first_name='user1',
        last_name='user1',
        email='user1@gmail.com',
        role=User.REGULAR
    )

    regular_user = User.objects.create_user(
        'user2',
        password='user2',
        first_name='user2',
        last_name='user2',
        email='user2@gmail.com',
        role=User.REGULAR
    )

    admin_user = User.objects.create_user(
        'admin',
        password='admin',
        first_name='admin',
        last_name='admin',
        email='admin@gmail.com',
        role=User.ADMIN
    )

    super_admin_user = User.objects.create_user(
        'super_admin',
        password='super_admin',
        first_name='super_admin',
        last_name='super_admin',
        email='super_admin@gmail.com',
        role=User.SUPER_ADMIN
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_admins_add)
    ]
